name: EGM722-Assessment
channels:
  - conda-forge
  - defaults
dependencies:
  - python>=3.11  # Minimum requirement for earthaccess
  - pip
  - numpy
  - pandas
  - scipy
  - earthaccess
  - geopandas
  - rasterio
  - rasterstats
  - rioxarray
  - xarray
  - xarray-spatial
  - shapely
  - matplotlib
  - matplotlib-scalebar
  - notebook